site_name: Concurrent for MLflow Docs
copyright: (c) Copyright 2022 The Concurrent AI Project. All Rights Reserved.
nav:
        - Home: 'index.md'
        - 'Architecture': 'files/arch.md'
        - 'FAQ': 'files/faq.md'
        - 'Free Hosted Service':
                - 'Sign Up': 'files/free.md'
                - 'Hello World': 'files/free-helloworld.md'
                - 'Test CLI': 'files/free-cli.md'
        - 'Roadmap':
                - 'Projects': 'files/roadmap-projects.md'
        - 'Admin':
                - 'Install Control Plane':
                        - 'Introduction': 'files/install-intro.md'
                        - 'AWS Install': 'files/install-parallels.md'
                        - 'AWS Update': 'files/aws-update.md'
                - 'Prepare k8s':
                        - 'Introduction': 'files/prepare-k8s-intro.md'
                        - 'EKS':
                                - 'Create New EKS': 'files/install-create.md'
                                - 'Use Existing EKS': 'files/install-existing.md'
                        - 'GKE':
                                - 'Create Service Account': 'files/create-service-account.md'
                                - 'Add k8s Role': 'files/add-k8s-role.md'
                                - 'Create Docker-In-Docker Service': 'files/create-dind.md'
                                - 'Enable GPU support': 'files/gke-enable-gpu.md'
                        - 'Add new k8s namespace': 'files/add-namespace.md'
        - 'Use':
                - 'MLproject': 'files/use-mlproject.md'
                - 'Data': 'files/use-data.md'

extra:
        analytics:
                provider: google
                property: G-PRSF2S114K

theme:
        name: material
        logo: https://docs.concurrent-ai.org/images/concurrent-logo.png
        favicon: favicon.ico
        palette:
                primary: blue
                accent: orange

markdown_extensions:
        - admonition
        - toc:
                # https://python-markdown.github.io/extensions/toc/
                permalink: true
        - pymdownx.highlight:
                # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
                use_pygments: true
                linenums: true
                linenums_style: pymdownx-inline
        - pymdownx.superfences
                # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
        - attr_list
                # https://python-markdown.github.io/extensions/attr_list/
