apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-serviceaccount-for-parallels-parallelsns
  namespace: parallelsns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-service-account-binding-parallelsns
  namespace: parallelsns
subjects:
- kind: ServiceAccount
  name: k8s-serviceaccount-for-parallels-parallelsns
  namespace: parallelsns
roleRef:
  kind: ClusterRole
  name: k8s-role-for-parallels-lambda
  apiGroup: ""
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-reader
subjects:
- kind: ServiceAccount
  name: k8s-serviceaccount-for-users-parallelsns
  apiGroup: ""
  namespace: parallelsns
roleRef:
  kind: ClusterRole
  name: pods-reader
  apiGroup: ""
