apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-role-for-concurrent-bootstrap
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - pods/log
  - secrets
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - post
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - create
  - get
  - list
  - watch
  - post
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - post
  - patch
  - delete
  - post
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-serviceaccount-for-parallels-REPLACE_WITH_NEW_NAMESPACE_NAME
  namespace: REPLACE_WITH_NEW_NAMESPACE_NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-service-account-binding-REPLACE_WITH_NEW_NAMESPACE_NAME
  namespace: REPLACE_WITH_NEW_NAMESPACE_NAME
subjects:
- kind: ServiceAccount
  name: k8s-serviceaccount-for-parallels-REPLACE_WITH_NEW_NAMESPACE_NAME
  namespace: REPLACE_WITH_NEW_NAMESPACE_NAME
roleRef:
  kind: ClusterRole
  name: k8s-role-for-concurrent-bootstrap
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-role-for-users-REPLACE_WITH_NEW_NAMESPACE_NAME
  namespace: REPLACE_WITH_NEW_NAMESPACE_NAME
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  - pods
  - pods/log
  - events
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-serviceaccount-for-users-REPLACE_WITH_NEW_NAMESPACE_NAME
  namespace: REPLACE_WITH_NEW_NAMESPACE_NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-serviceaccount-for-users-REPLACE_WITH_NEW_NAMESPACE_NAME-binding
  namespace: REPLACE_WITH_NEW_NAMESPACE_NAME
subjects:
- kind: ServiceAccount
  name: k8s-serviceaccount-for-users-REPLACE_WITH_NEW_NAMESPACE_NAME
  namespace: REPLACE_WITH_NEW_NAMESPACE_NAME
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: k8s-role-for-users-REPLACE_WITH_NEW_NAMESPACE_NAME
  apiGroup: ""
---
