AWSTemplateFormatVersion: 2010-09-09
Description: Wrapper that creates the k8s role
Resources:
  CreateK8sRole:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: eks-for-concurrent
      Namespace: "default"
      Url: s3://docs.concurrent-ai.org/cft/example-cluster/k8s-service-role-for-parallels.yaml
