apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-role-for-users-default
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-serviceaccount-for-users-default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-serviceaccount-for-users-default-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-serviceaccount-for-users-default
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-role-for-users-default
  apiGroup: ""
