apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: parallels-super-high-for-dind
value: 10000
globalDefault: false
description: "parallels highest prio for docker in docker pod"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: hpe-hdd-storage
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  
  hostPath:
    path: "/etc"
---
# PVC for storing dind data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: docker-dind
  name: docker-dind-data
  namespace: parallelsns
spec:
  storageClassName: hpe-hdd-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-dind
  name: docker-dind
  namespace: parallelsns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-dind
  template:
    metadata:
      labels:
        app: docker-dind
    spec:
      priorityClassName: parallels-super-high-for-dind
      containers:
        - image: docker:20.10.18-dind
          args: [--insecure-registry=registry-service:5000, --insecure-registry=registry-service:443, --insecure-registry=registry-service.parallelsns, --insecure-registry=registry-service.parallelsns:5000, --insecure-registry=registry-service.parallelsns.svc.cluster.local, --insecure-registry=10.241.17.223:30810, --insecure-registry=10.241.17.209:30810, --insecure-registry=10.241.17.223:31386, --insecure-registry=10.241.17.209:31386, --insecure-registry=hpe-gw1-priv.infinstor.com:10019, --insecure-registry=hpe-gw2-priv.infinstor.com:10019, --insecure-registry=gateway.hpecatalystpoc.com:10019 ]
          name: docker-dind
          env:
            - name: DOCKER_HOST
              value: tcp://0.0.0.0:2375
            - name: DOCKER_TLS_CERTDIR #Disable TLS as traffic is not going outside of network.
              value: ""
          volumeMounts:
            - name: docker-dind-data-vol #Persisting the docker data
              mountPath: /var/lib/docker/
          ports:
            - name: daemon-port
              containerPort: 2375
              protocol: TCP
          securityContext:
            privileged: true #Required for dind container to work.
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
      volumes:
        - name: docker-dind-data-vol
          #emptyDir: {}
          persistentVolumeClaim:
            claimName: docker-dind-data
---
## Service for exposing docker-dind
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-dind
  name: docker-dind
  namespace: parallelsns
spec:
  ports:
    - port: 2375
      protocol: TCP
      targetPort: 2375
  selector:
    app: docker-dind
