apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdIRENDQkFTZ0F3SUJBZ0lVUHRIenp5Ky9UMHdQMEFCQ3dyZTUzbWxTQ3g0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1p6RUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SSXdFQVlEVlFRS0RBbEpibVpwYm5OMApiM0l4TnpBMUJnTlZCQU1NTG5KbFoybHpkSEo1TFhObGNuWnBZMlV1Y0dGeVlXeHNaV3h6Ym5NdWMzWmpMbU5zCmRYTjBaWEl1Ykc5allXd3dIaGNOTWpJeE1qRTBNVFUwT0RVNFdoY05Nekl4TWpFeE1UVTBPRFU0V2pCbk1Rc3cKQ1FZRFZRUUdFd0pWVXpFTE1Ba0dBMVVFQ0F3Q1EwRXhFakFRQmdOVkJBb01DVWx1Wm1sdWMzUnZjakUzTURVRwpBMVVFQXd3dWNtVm5hWE4wY25rdGMyVnlkbWxqWlM1d1lYSmhiR3hsYkhOdWN5NXpkbU11WTJ4MWMzUmxjaTVzCmIyTmhiRENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFOSnlEL1JqcmQ1VzJtaHIKZXRCaW9ZZ25pbTBjS0h0bEZSQmxJQ0FzbGprV1ljaXVjZ1lvMzdiQk1DS09pdXJjSDkzamg2THMyMkc1YTRQKwpZaHBTZDdTTFI3ZU11R1ZpS1FnY0lTZFRWbStyR0pkb3hhWnB2TGtCNU5KSW85U3oyQVF5MmJ5ekxGaklYV0RECi9pOW9hOVV3OWl6aHFCamZxU1grRzBKNE1UcFZWdVdXYStwM3ZvVVBFcmtzdk0wT09qKzVpUTVuVzlvRVJIRE4Kbm40RFRkeXR5cEUybWl5bEJCNnhHcjJsOHovNGcyTTVpNFRMMHFRSjk4OEppU1FHa0tpU3grQ2h4RS9sQkN6KwpkQWtUS3g5YklmRnN6c2VjUXVEQ3ZvSlE4bnNUM0ZWd3FLWjNZUUlZRlRPTW9RckUxY0tiYUhwVkFhYW9EMllkCithOHhoSzlyVW5YckM1RXRSSWZEQmU1aWk4UnZLeW1JQzlGMnd1ai8xdi90djBHQXU3bTNoSkVUa2RURndNRUEKdzhwcEtpcnpOdGsxNHY3OVdSRlNKdFhJYkJ1U0lKemgyQkt4NU92NVcxMFV3TGdBWEZKU2JVWHBWM01Fb2tpVwpjQXFUeDdOTCt0dkRMaVVFQVFvVTF0amx4RVloV2h6T3JlSGN5SWp1YUxYenp5MzMwN0dRb29YSTJmQmN3ejBKCnVWWHlZZDJPdENyelYyM2ZvWUJtem1KRE5hMHJxTGdWS0Y1NUlxeVY4bjhZMk9KUWFjMWFUOGpmdjZFRWhVMGkKR3FZOStvR21VYW1EQVloZTBJQWl5enR6TTczcUlTU1pURzFONFQ4dDBxY0FITVRRVXE0ZjFmb2dkWkNuam5UMwpIMzhZRFozaThkMW5DbEs0WkZRZGhRdmlJSkdwQWdNQkFBR2pnYjh3Z2J3d0hRWURWUjBPQkJZRUZOUjhYV3NCCkNCMFdJeWt1NkJPZElIS29lY1doTUI4R0ExVWRJd1FZTUJhQUZOUjhYV3NCQ0IwV0l5a3U2Qk9kSUhLb2VjV2gKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3YVFZRFZSMFJCR0l3WUlJUWNtVm5hWE4wY25rdGMyVnlkbWxqWllJYwpjbVZuYVhOMGNua3RjMlZ5ZG1salpTNXdZWEpoYkd4bGJITnVjNEl1Y21WbmFYTjBjbmt0YzJWeWRtbGpaUzV3CllYSmhiR3hsYkhOdWN5NXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUEKcFVyV21nWGpxa1VlNERCQ0szdjJjREFwdmx1NE1uM0JaZWJ0VGVQdnhmQnpJTC9KY3ZHK3R1Y3lxSWFxSGRHSwp0WUhubmgxZGtXRW81VXNxTmRHWWREWURNWjBZaEZ6NXhHMVQ1L2JiZnI5Z09PSEJYZlE4TmxieFc5RWhrWHFGClNVek91UFFDY1psQlZXcWwycitoQ0x3Q2dJTzU3WWluZWxTY3RwZ1l4alFGLzJJYVJFbGVCcXRKWjBVcjZHR1QKVEo2emtZczNLdTFLYW44K2N3UzQvUmNXb3N5cThEYjFhUXFkbzJ2eXNrcUZxaVFqYmRDa1NxR2E0ZEZxOVpnbwp4VW1HZDd2UGxQYmEzeU9BVjFHQWZwMjQ0T1cyZmQzZnRjc1hxbzFQWW9EWmRmdVlobk1zVENvN2dRaEU2SGFjCmNHbVllMUltVVQwczlXUjJMSmJRTTNKWVdHdjdWV3FVenk4ZVdWZUs5ZEczaFFHWnRxT2pBOC9NT1Awbm45R3YKa0tyOExnUVhnRXlSZG9YOTdXRFpIZDF0bkZLK1VZRmRwd0dmUnpuN2NCM0VXNzc1d1FZODhQa3ViSGZ4UnRZMwp4WEl6cFE2V2ZuNWY0T2F4UUdLdWdIb3J3K2sxZGJOQzg3MFFHdExSRkVoc3p6NER1ZDBmeExJZk9RSmpMU0ZVCnBrQThzeTdocERpTXRtQUlxNm53cHF0K2l4dHd3RFRjWVU2R2tRbXdFcWhZRllEWVhHaUl0MDU2YVRxSVFYNW0KNXJOTDVTT3Qrclg1UEwvZHlFalBKekdjWnZXQmUra0VZZzdoYk1waGpDL0w1dXc2Q2ZLaytEMDVtdzZVK1M4KwpWcm03anpGN2FSSGR4VDM0VGU4NlNxWUVrQWs0a2RVZ3RoY01Fd3dUNGZzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRRFNjZy8wWTYzZVZ0cG8KYTNyUVlxR0lKNHB0SENoN1pSVVFaU0FnTEpZNUZtSElybklHS04rMndUQWlqb3JxM0IvZDQ0ZWk3TnRodVd1RAovbUlhVW5lMGkwZTNqTGhsWWlrSUhDRW5VMVp2cXhpWGFNV21hYnk1QWVUU1NLUFVzOWdFTXRtOHN5eFl5RjFnCncvNHZhR3ZWTVBZczRhZ1kzNmtsL2h0Q2VERTZWVmJsbG12cWQ3NkZEeEs1TEx6TkRqby91WWtPWjF2YUJFUncKelo1K0EwM2NyY3FSTnBvc3BRUWVzUnE5cGZNLytJTmpPWXVFeTlLa0NmZlBDWWtrQnBDb2tzZmdvY1JQNVFRcwovblFKRXlzZld5SHhiTTdIbkVMZ3dyNkNVUEo3RTl4VmNLaW1kMkVDR0JVempLRUt4TlhDbTJoNlZRR21xQTltCkhmbXZNWVN2YTFKMTZ3dVJMVVNId3dYdVlvdkVieXNwaUF2UmRzTG8vOWIvN2I5QmdMdTV0NFNSRTVIVXhjREIKQU1QS2FTb3E4emJaTmVMKy9Wa1JVaWJWeUd3YmtpQ2M0ZGdTc2VUcitWdGRGTUM0QUZ4U1VtMUY2VmR6QktKSQpsbkFLazhlelMvcmJ3eTRsQkFFS0ZOYlk1Y1JHSVZvY3pxM2gzTWlJN21pMTg4OHQ5OU94a0tLRnlObndYTU05CkNibFY4bUhkanJRcTgxZHQzNkdBWnM1aVF6V3RLNmk0RlNoZWVTS3NsZkovR05qaVVHbk5Xay9JMzcraEJJVk4KSWhxbVBmcUJwbEdwZ3dHSVh0Q0FJc3M3Y3pPOTZpRWttVXh0VGVFL0xkS25BQnpFMEZLdUg5WDZJSFdRcDQ1MAo5eDkvR0EyZDR2SGRad3BTdUdSVUhZVUw0aUNScVFJREFRQUJBb0lCL3l1UmNid201dGdoSXhaN0tmSDZlWGEyCnVQSGQ0b09wYWJMN1BLdHNqNjFCOVB5WElRUWxjaXRqMDVOVDcyNndJK2pNTWtpSXdPSjZnTWZTNG55UWxqZksKbmc1aUU4cnBoNVVtUGJibWlmNlViWUxyTGdCRjQ4eHBsL1h4RS9uMVFjT2N3M2ROb09EQW1wUnQvekhSYklHMgpvVUNwZHlPdktsV3pSZkY4OExRaTl0cVJTY1pCQkRDSDdsaG42cTZKUTRYdDQzSVg4K3d1OWZ4a2xXdUJRNTFzClhZT3l5amh6OFdacFJCLy9PMTBERmpCMHVXM0V4TmN4T1J5ajNNQ1ltMXBMQ1JaNFp5d2pQYm9TOC9MdEJRQjQKM1k0ZCtMRmFxSDNmMDVFbk1ReEtFRk9mLzBwM2JKNENYbUZOdkFsK3RzS1RhZzNwaTIzMVhUckcrZXBMVml5YQp3NE9xckc0Y2ZrZE0vQTE0aUlmSm9tWTBycU9DZUhrMllkY0VNRVVVZnNBeXQzVW45MDEyRm1XbmM1ekpBNUp2CnRlWG1VdlFSdENuT0hiVXNlaU8wTTNKNS9xL2pmNnVIS1FDOFRmQXp1SytCU0RYbTdadWxoaHU4T1dyTHMyL1MKdFkzR1UwMU1LbnRxOWw3bXJjY2JxVGowakpqa0F4dm5TKzR2Q0U1ZUthN0lBcy9RSG52bUlSdFZJbmVpSk9mbwphMTZlNFM0aEdiNWRNYnpvT01GWmFySWFaU0FOaDFyT0RlaGxaNTV5dDFSclN3T3JLcEtDRmh4eWhhU2hpRk54CmhseTN4NzFlTUdXQWRzb1ZGR2wzU1M3VFhRUE45WUo5MVBkOXBIdjk4aHBiSHo4QnpHcmhaWlhEOEpKZ0NaWUIKSm1aYStxUVY3VGpkcVJGVjFwVUNnZ0VCQVBaL1NYV1hSb2lLVExjSXBHQUJxckRvMTI0Q1JwT3JOc2RJejNsRApTTzM5eGJ1MzVWajV2eFVJQ2NGQlVrcU14c1BWMWtKQzk3TzBBR0xjK0RzUEpZQmMrUXRHaGhRUE1SYnN5a0kxCm40UDhBWUhET0RsUXV1bG1SWnpPV1VyZXRMc3dUVTBEeW8vNnVQS01XNVcrOC9PS3VzQkpRMVBkenZLc3JCZUsKR2o3cGx1MTJCMmU1bzVIUE9NSERUNThYVnRYZTNBSXFFQkxXZS9VQXJFbkZjM2dWUStFekdEaFdDK3RGTmhQdQpZUzY2Vk5BeUNld2NRTEJBY1Biejl6NHpWNThPcTVEbzErdGhyUmt6QzZIa2hyem9TVVd1TEk3ckt3RlRFRHk1CmU1ZjRvMUFXa28vTTZhM2IvMVlGSDNSL2FVdE9xaXdiWGx2OStNN1JTUU54ZExNQ2dnRUJBTnFPK2hQeGFLbnQKZXRXV0pmKzFrUEtZWElpOUFyY1h4eEtjYlZLSkZFSERtYkVXeVZNZEhVbG5TV2JoeVJiQ1RyQnQ0d1hmaDgyMwpRNXZUZHJmeEx5aEZVMGhib0gvMDE3eWNUN1FUNnBGWE1yMS85S1d5Skd5MTh6dWx5VmJValBDd2xjamNzemZOCmEwdWRuOGlKU1l4TFh4UlRkY1RFRmlvVHlMOTMxOU9oYURDNmlPUGdFcjVVbDhrMXlLZEg2K2VRV0dpNloyclYKU3FjOFVBejBSVzhmVCtGb0dKNCtsV1VVRzE4dURlcnZWaE11K1Jsb1FCY2dEcmovbXZCd2JjUmNGT3lVRUZiTAp2R0UyTFMyM0Y0OUpDeGNFZFJFelduTk5Fc29hOUFyTmdodnhvT2RpK3FPbWpQOHNFTlcrc2ZtRVJCd2ZSaWxiCk5hc0xCb05kWmpNQ2dnRUJBSmlzbmtOSFAxaXkwSEZOMlFIZUJtc3N6TUpHaHBCUUs4MmpPMTVRWG91Sjh6OGgKMTl3VVZGWWlkR2hPblRtdm1DMFQ5WEYxS1JjVkZtZ2xsVnAvTnlzYWF1YWc5OHJVM2dMbEJ5R2JOUUg2eExRcQp4bGc1dUl0MzNRWVNpUnZtZE9xOE1DVFRoRk5KWitSVEt5YkU3elNaYUxKUXJuTHpuNHFQaU1mTHNoWGxlS1g3CnhQcHA4UFlPODRpUUFIRDVjNzlrR2NEOWJKYytZZWlPVWlnZk5EWGNkZjYyTnZvdDBaUVhlamMrSHROaWRjVysKT0ljVnVMdHlMb1hHOWd5QW9IVFVFVS9mNkZ6U1V2U1l1VXU4ei9lUnFGQ1FZT2prbis1aUZGeUlSaFVLMjV4dgpYcmZTbzZvYjZUck9VWDFHcldFSGlEOXBkRGhtUmdWVGUzVzJnQ0VDZ2dFQU9ha0MzUVFSZ3RNK1Z0OFlBMUJaCmYwY25Fb1FiRlViV3BGaFVselBHL2xxbVQ0d2RiU24vTWdCbjR4YXFRTERlcGJrMzdiSzlWMDZFTGJZcVdmanQKWWdoNElsemFDU2dGU3FOS2U4M05VcTdZbWhvSjV6VUtXd3Zkc2R6Wk0yazhEYnZvcUdkaGVOVmUrMElJaDVXQQpxOXl1cHVRbDY5VjNxMzR3dGlMZDg5MWZhWXVzMWNHbDhFVE5EcTU3MDNZc0RKbU9XWUxrQ2RGZnNxTTgwMDRXCmkyeU5YSUJrRGt1Z2lsdzFwSFM0QTBWRlJpWmNYWkdkWnZ4MEplWjViL21aVy9hWEpwc2hmR1NmdkYzWXFYam0KWkV6MitnbVpBUUsxV0RuN1BRckRXNTVBTnpNV0tqVjR2bmdRTnJuZmJ5U3lPNHZqbEMvRUNPRWhWWkRCRlNNcwo5UUtDQVFFQThXUzNvTG1TUlJGcnY1T1o2QmRKbENRRlUySWNjU3M1aVNvbnczcnBPRmZJcmZ5TnhPR3hqUXdGCllnYkgvYnQrK3BqdFZ4R3pLcCtvNDh6M1lqRmpoenBuK05YdUcwYVRzQU9ISTJuTjBoWGlOMGwreVhDQWVXK3AKbnkzTjZpRWNEQmhGa2hCMUxmMk5pSWlYajFkd2FnazVmTENJZWNPYVRIeDZxMWpDcDhodlZ4Q3NSaEVEZ2RicQo0MVN3a1lYTVA0Yk9yK21qWnhRS09CUFc5dWZLa1lhSCtiR3pQdThhT1FFcXhyemJaSjJab1FabXVNdzJKOXc5Clg1VnF5MVdrQlFjOTA1T05PRzJKcitlQXpoWisrd0piOHVXNkt2bTd4N2VtUlVXQ3V2dHVPbjdBemlZS2k4cUkKSTltSDNnNnhKUGswRVlWeGxseFJsd0NwRWhJcjdnPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-cert
type: kubernetes.io/tls
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  #namespace: infinstor
  namespace: parallelsns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      #storage: 50Gi
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: registry
  name: registry
  #namespace: infinstor
  namespace: parallelsns
spec:
  replicas: 1
  selector:
    # see spec.template.metadata.labels.run below
    matchLabels:
      run: registry
  template:
    metadata:
      labels:
        run: registry
    spec:
      #nodeSelector:
        #node-type: worker
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
        volumeMounts:
        - name: registry-certs
          mountPath: "/certs"
          readOnly: true
        - name: registry-data
          mountPath: /var/lib/registry
          subPath: registry
        #resources:
          #limits:
            #cpu: 500m
            #memory: 500Mi
          #requests:
            #cpu: 300m
            #memory: 300Mi
      volumes:
      - name: registry-certs
        secret:
          secretName: registry-cert
      - name: registry-data
        emptyDir: {}
        #persistentVolumeClaim:
        #  claimName: registry-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  #namespace: infinstor
  namespace: parallelsns
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  type: NodePort
  #type: LoadBalancer
  #type: ClusterIP
  selector:
    run: registry
  ports:
    - name: registry-tcp
      protocol: TCP
      #port: 443
      port: 5000
      targetPort: 5000
    - name: registry-tcp-ssl
      protocol: TCP
      port: 443
      targetPort: 5000
  #loadBalancerIP: 10.211.55.250